name: RSS
on:
  # Schedule daily updates
  schedule: [{cron: "20 0,12 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: rss.svg
          user: fu-jw
          template: classic
          base: header, activity, community, metadata
          config_timezone: Asia/Shanghai
          
          plugin_rss: yes
          plugin_rss_source: https://fu-jw.github.io/rss
          plugin_rss_limit: 5
          
