name: Social Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: anzhiyu-c/social-readme@master
        with:
          blog_rss_link: https://fu-jw.github.io/atom.xml
          blog_limit: 5 # blog数量
          commit_message: Updated social rss by social-readme # commit说明
